    name: Deploy to GitHub Pages

    on:
      push:
        branches:
          - main
      workflow_dispatch:

    jobs:
      Deploy:
        runs-on: ubuntu-24.04
        permissions:
          pages: write
          id-token: write # Necessary for the OIDC requested token in deploy-pages action!
        concurrency:
          group: ${{ github.workflow }}-${{ github.ref }}
        steps:
          - uses: actions/checkout@v4

          - name: Setup Node
            uses: actions/setup-node@v4
            with:
              node-version: "20"
              cache: "npm"

          - run: npm ci
          - run: npm run build

          - name: Upload GitHub Pages artifact
            uses: actions/upload-pages-artifact@v3.0.1
            with:
              path: dist

          - name: Deploy
            uses: actions/deploy-pages@v4

